source 'https://rubygems.org'

gem 'bootstrap-sass', '~> 3.0.3.0'
gem 'bourbon'
gem 'font-awesome-sass'
gem 'haml'
gem 'haml-rails'
gem 'jquery-rails'
gem 'jquery-validation-rails'
gem 'mysql2'
gem 'omniauth'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'
gem 'rails', '4.1.2'
gem 'rake'
gem 'sass-rails', '~> 4.0.0'
gem 'therubyracer'
gem 'uglifier', '>= 1.3.0'
gem 'unicorn'

group :development do
  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'quiet_assets'
end
